import '../style/global.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>A Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className='flex flex-col px-4'>
        <header className='mb-8'>
          <div className='container mx-auto bg-slate-50 py-8 px-4 rounded-b-lg flex justify-center'>
            <h1 className='text-3xl text-slate-400'>$⏉☈∈₳㎡ ℉ τΗ❍⊔𝙶𝚑㈦</h1>
          </div>
        </header>
        <main className='py-4 flex-1'>
          <div className='container mx-auto'>
          {children}
          </div>
        </main>
        <footer className='mt-8 py-4'>
          <div className='container mx-auto flex justify-center'>
            Made by Luke with NextJS
          </div>
        </footer>
      </body>
    </html>
  )
}
